######################################################################
# Automatically generated by qmake (2.01a) ?? 26. ??? 22:21:54 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += mainwindow.cpp
