######################################################################
# Automatically generated by qmake (2.01a) ?? 26. ??? 22:21:54 2014
######################################################################

TEMPLATE = app
TARGET = my_editor
DEPENDPATH += .
INCLUDEPATH += .

greaterThan(QT_MAJOR_VERSION, 4) {
   QT += widgets
}

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += mainwindow.cpp \
    main.cpp
